name: "Check and report Android Lint result"
description: "A GitHub Action to check and report the results of Android Lint in Job Summaries"
author: hidakatsuya
branding:
  color: green
  icon: check
inputs:
  result-path:
    description: "Path or glob path pattern for Android Lint result XML file"
    required: true
  fail-on-warning:
    description: "Indicates whether the action should fail if there is a severity warning issue"
    default: true
  follow-symbolic-links:
    description: "Indicates whether to follow symbolic links"
    default: true
runs:
  using: "node20"
  main: "dist/index.js"
