name: Prepare dist

on:
  workflow_dispatch:

jobs:
  prepare-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run prepare

      - run: git status

      - run: |
          git add .
          git commit -m "Built and updated the distribution scripts"
          git push origin HEAD
        env:
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: action@github.com
          GIT_COMMITTER_NAME: GitHub Actions
          GIT_COMMITTER_EMAIL: action@github.com
