name: "units-test"

on: push

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  action-test-success:
    runs-on: ubuntu-latest

    env:
      RUN_FAILURE_TEST: false

    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        result-path: "__tests__/xml/success*.xml"

  action-test-success-with-warnings:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        result-path: "__tests__/xml/failure2.xml"
        fail-on-warning: false

  action-test-error:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        result-path: "__tests__/xml/failure*.xml"
      continue-on-error: true
