name: "units-test"

on: push

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version: 24
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  action-test-success:
    runs-on: ubuntu-latest

    env:
      RUN_FAILURE_TEST: false

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: ./
      with:
        result-path: "__tests__/xml/success*.xml"

  action-test-success-with-warnings:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: ./
      with:
        result-path: "__tests__/xml/failure2.xml"
        fail-on-warning: false

  action-test-error:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: ./
      with:
        result-path: "__tests__/xml/failure*.xml"
      continue-on-error: true
